SouJunior/code-challenge

javascript/pauloruan/01-return-the-sum-of-two-numbers/README.md
javascript/pauloruan/01-return-the-sum-of-two-numbers/addition.js

01 - Return the Sum of Two Numbers

---

javascript/pauloruan/01-return-the-sum-of-two-numbers/README.md
javascript/pauloruan/01-return-the-sum-of-two-numbers/addition.js
javascript/pauloruan/02-football-points/README.md
javascript/pauloruan/02-football-points/footballPoints.js

02 - Football Points

---

javascript/pauloruan/01-return-the-sum-of-two-numbers/README.md
javascript/pauloruan/01-return-the-sum-of-two-numbers/addition.js
javascript/pauloruan/02-football-points/README.md
javascript/pauloruan/02-football-points/footballPoints.js
javascript/pauloruan/03-reverse-an-array/README.md
javascript/pauloruan/03-reverse-an-array/reverse.js

03 - Reverse an Array

---

javascript/pauloruan/01-return-the-sum-of-two-numbers/README.md
javascript/pauloruan/01-return-the-sum-of-two-numbers/addition.js
javascript/pauloruan/02-football-points/README.md
javascript/pauloruan/02-football-points/footballPoints.js
javascript/pauloruan/03-reverse-an-array/README.md
javascript/pauloruan/03-reverse-an-array/reverse.js
javascript/pauloruan/04-area-of-a-rectangle/README.md
javascript/pauloruan/04-area-of-a-rectangle/area.js

04 - Area of a Rectangle

---

bash/amepebbles/2.md
bash/amepebbles/2.sh

PR para o segundo desafio escrito em Bash (Shell Linux).

Football Points

---

javascript/backtoaldo/Football Points/footballpoints.js
javascript/backtoaldo/Football Points/readme.md.txt
python/backtoaldo/Area of a Rectangle/areaofarectangle.py
python/backtoaldo/Area of a Rectangle/readme.md.txt
python/backtoaldo/Return the Sum of Two Numbers/readme.md.txt
python/backtoaldo/Return the Sum of Two Numbers/returnthesumoftwonumbers.py
python/backtoaldo/Reverse an Array/readme.md.txt
python/backtoaldo/Reverse an Array/reverseamarray.py

Ambos os exercicios em diferentes pastas - correspondentes ao meu user e linguagem. Todos seguem com readme de explicação dos exercicios propostos.

Exercicios

---

javascript/laporeon/README.md
javascript/laporeon/index.js

Enviado solução para o desafio 03 - reverter um array - e como executar.

feat: adiciona solução para o desafio 03

---

python/laporeon/README.md
python/laporeon/index.py

Adicionando solução para o desafio 01 em Python e como executar o código.

feat: adiciona solução para desafio 01

---

javascript/felpfsf/futebol-pontos/index.html
javascript/felpfsf/futebol-pontos/main.js
javascript/felpfsf/futebol-pontos/readme.md
javascript/felpfsf/futebol-pontos/styles.css
javascript/felpfsf/readme.md
javascript/felpfsf/retorne-a-soma/index.html
javascript/felpfsf/retorne-a-soma/main.js
javascript/felpfsf/retorne-a-soma/readme.md
javascript/felpfsf/retorne-a-soma/styles.css

Desafio 1 Retorne a soma de dois números
Resolução do desafio, basta executar o index.html no navegador (testado em chrome, moz e opera). Um front para o usuário entrar com os valores e após clicar ou apertar enter o resultado é exibido na tela.
Dentro da pasta do desafio tem um readme documentando melhor.

resolução desafios - lang: javascript

---

java/thomascouto/Football.java
java/thomascouto/Rectangle.java
java/thomascouto/ReverseArray.java
java/thomascouto/Sum.java

feat: Java Challenge 1 2 3 4

---

php/jeffersonrodrigo/README.md
php/jeffersonrodrigo/footballPoints.php
php/jeffersonrodrigo/return_sum.php

Fazendo o pull de um dos desafios apresentados, no caso o da soma de 2 números

Commit do desafio Soma de 2 números

---

javascript/systemoflima/1. Return the Sum of Two Numbers/index.js
javascript/systemoflima/2. Football points/index.js
javascript/systemoflima/3. Reverse an Array/index.js
javascript/systemoflima/4. Area of a Rectangle/index.js
javascript/systemoflima/README.md
javascript/systemoflima/index.js

Posteriormente criarei uma interface para cada desafio para que seja executado direto no navegador

desafio concluido, by SystemOfLima

---

bash/amepebbles/4.md
bash/amepebbles/4.sh

Último desafio completo! Foi bem divertido, obrigado por disponibilizar o repositório. :D

Area of a Rectangle

---

csharp/laporeon/FootballPoints.cs
csharp/laporeon/README.md

Adicionando solução em C# para o desafio 02 - Football Points.

feat: adiciona solução para desafio 02

---

javascript/felpfsf/reverter-array/index.html
javascript/felpfsf/reverter-array/main.js
javascript/felpfsf/reverter-array/readme.md
javascript/felpfsf/reverter-array/styles.css

O programa exibe o valor digitado pelo usuário e logo em seguida o mesmo valor invertido. Caso o campo esteja vazio uma mensagem de erro é exibida.
O array é criado através do método split com o auxílio de uma regex. Uma variável armazena o valor da nova array e outra recebe o valor da array com reverse.
Segue uma imagem demonstrando a tela

Resolução Desafio lang: javascript

---

typescript/maztt/calculator-football-points.ts
typescript/maztt/calculator-rectangle-area.ts
typescript/maztt/calculator-sum-of-two-numbers.ts
typescript/maztt/readme.md
typescript/maztt/reverse-array.ts

Adicionando pasta e soluções em TypeScript.

add: TypeScript solutions

---

javascript/brunoGuimaraes/DesafioDois/index.js
javascript/brunoGuimaraes/DesafioQuatro/index.js
javascript/brunoGuimaraes/DesafioTres/index.js
javascript/brunoGuimaraes/DesafioUm/index.js
javascript/brunoGuimaraes/Readme.md
javascript/brunoGuimaraes/index.js

Segue os desafios feitos em JavaScript. 
Toda documentação se encontra no arquivo README da pasta.

:sparkles:	feat: Entrega dos desafios feitos do hacktober fest - Sou Júnior

---

javascript/theussoliveira011/README.md
javascript/theussoliveira011/reverse_array.js

this is my solution to exercise reverse_array in javascript

solution reverse_array

---

javascript/rafaelasoperes/index.js
javascript/rafaelasoperes/readme.md

Adicionando minha contribuição.

soma de 2 números

---

javascript/w3ssfs/Return_the_sum_of_two_numbers/README.md
javascript/w3ssfs/Return_the_sum_of_two_numbers/desafio_01.js
javascript/w3ssfs/area_of_rectangle.js/README.md
javascript/w3ssfs/area_of_rectangle.js/desafio04.js
javascript/w3ssfs/football_points/README.md
javascript/w3ssfs/football_points/desafio_02.js
javascript/w3ssfs/reverse_array/README.md
javascript/w3ssfs/reverse_array/desafio03.js

desafios completos - _hacktoberfest 2022_

desafios completos !

---

javascript/williamluqui/1-Return the Sum of Two Numbers.js
javascript/williamluqui/2-Football points.js
javascript/williamluqui/3-Reverse an Array.js
javascript/williamluqui/readme.md

Desafio resolvido com sucesso no edabit.com

resolução do desafio 1

---

php/yanbrasiliano/01-return-the-sum-of-two-numbers/app.php
php/yanbrasiliano/02-football points/app.php
php/yanbrasiliano/readme.md

Segue o primeiro desafio, com readme.md geral(será atualizado conforme a finalização dos desafios).

Desafio 0 - Retorno de Soma.

---

php/yanbrasiliano/01-return-the-sum-of-two-numbers/app.php
php/yanbrasiliano/02-football points/app.php
php/yanbrasiliano/readme.md

Finalizando desafio football points.

Desafio football points - Finalizado.

---

csharp/marcostech/Desafio-Array/Inversora.cs
csharp/marcostech/Desafio-Array/Program.cs
csharp/marcostech/Desafio-Array/README.md

Desafio 3 - invertendo um array usando C#.
Usando a abstração fornecida pela classe Array nativa do C#, nela o metodo Reverse() faz todo o trabalho!

Desafio Inverter um Array

---

java/g-filipe/src/challenge1Sum/SumOfTwoNumbers.java
java/g-filipe/src/challenge2Football/FootballPoints.java
java/g-filipe/src/challenge3ReverseArray/ReverseArray.java
java/g-filipe/src/challenge4AreaOfARectangle/AreaOfARectangle.java

Olá, tudo bem? Me chamo Filipe Galvão.
Seguem minhas resoluções dos desafios em Java. 
Parabéns pela iniciativa.
Obrigado.
Atenciosamente,
Filipe

SouJunior Code-Challenge (Java) by Filipe Galvao

---

javascript/lucianosants/desafio_1/README.md
javascript/lucianosants/desafio_1/index.html
javascript/lucianosants/desafio_1/index.js
javascript/lucianosants/football_points/README.md
javascript/lucianosants/football_points/index.js

Adicionado a solução do primeiro desafio

desafio 01

---

javascript/zirtaebn/challenge1/README.md
javascript/zirtaebn/challenge1/index.js

Resolução do primeiro desafio proposto.

challenge 1: sum of two numbers

---

javascript/zirtaebn/challenge2/README.md
javascript/zirtaebn/challenge2/index.js

Resolução do segundo desafio proposto.

challenge 2: football points

---

go/leonardovictorribeiro/challenge01/main.go
go/leonardovictorribeiro/challenge01/readme.md
go/leonardovictorribeiro/challenge02/main.go
go/leonardovictorribeiro/challenge02/readme.md

Adiciona a resolução na linguagem Go do desafio Return the Sum of Two Numbers.

Adicionado challenge 01

---

php/jeffersonrodrigo/Area_of_rectangle.php

Desafio do calculo de área no PHP

desafio calculo de area

---

javascript/zirtaebn/challenge3/README.md
javascript/zirtaebn/challenge3/index.js

Resolução do terceiro desafio proposto.

challenge 3: reverse an array

---

go/vivi3008/areaRectangle/main.go
go/vivi3008/footballPoint/main.go
go/vivi3008/readme.md
go/vivi3008/reverseArray/main.go

feat: challenges in go

---

javascript/zirtaebn/challenge4/README.md
javascript/zirtaebn/challenge4/index.js

Resolução do quarto desafio proposto.

challenge 4: area of a rectangle

---

.idea/.gitignore
.idea/code-challenge.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/inspectionProfiles/profiles_settings.xml
.idea/misc.xml
.idea/modules.xml
.idea/vcs.xml
python/tlsabara/README.md
python/tlsabara/code-challenge/__main__.py
python/tlsabara/code-challenge/add/README.md
python/tlsabara/code-challenge/add/function.py
python/tlsabara/code-challenge/add/test_add.py
python/tlsabara/code-challenge/area/README.md
python/tlsabara/code-challenge/area/function.py
python/tlsabara/code-challenge/area/test_area.py
python/tlsabara/code-challenge/football_points/README.md
python/tlsabara/code-challenge/football_points/function.py
python/tlsabara/code-challenge/football_points/test_football_points.py
python/tlsabara/code-challenge/reverse/README.md
python/tlsabara/code-challenge/reverse/function.py
python/tlsabara/code-challenge/reverse/test_reverse.py
python/tlsabara/code-challenge/utils/README.md
python/tlsabara/code-challenge/utils/functions.py

Desafio Code-challange - tlsabara
